//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwoFish.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Edit
    {
        public int EditID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> FishID { get; set; }
    
        public virtual Fish Fish { get; set; }
        public virtual User User { get; set; }
    }
}
