//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwoFish.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FishOfTheDay
    {
        public int FishID { get; set; }
        public string Type { get; set; }
        public string FSB { get; set; }
        public string Habitat { get; set; }
        public string Features { get; set; }
        public string History { get; set; }
    
        public virtual Fish Fish { get; set; }
    }
}
