//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwoFish.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fish
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fish()
        {
            this.Edits = new HashSet<Edit>();
        }
    
        public int FishID { get; set; }
        public string Type { get; set; }
        public string Weight { get; set; }
        public string History { get; set; }
        public string Picture { get; set; }
        public Nullable<int> HabitatID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Edit> Edits { get; set; }
        public virtual FishOfTheDay FishOfTheDay { get; set; }
    }
}
